name: Publish Protocol
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - src/boilerplate/**
      - src/protocol/**
      - src/*.html
      - src/*.include
      - src/protocol.bs
  push:
    branches:
      - main
    paths:
      - src/boilerplate/**
      - src/protocol/**
      - src/*.html
      - src/*.include
      - src/protocol.bs
jobs:
  main:
    name: Publish Protocol to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: src/protocol.bs
          DESTINATION: protocol/index.html
