name: Publish Protocol
on:
  workflow_dispatch: {}
  pull_request:
    branches-ignore:
      - gh-pages
    paths:
      - src/boilerplate/**
      - src/examples/**
      - src/protocol/**
      - src/*.html
      - src/*.include
      - src/protocol.bs
    types:
      - closed
  push:
    branches-ignore:
      - gh-pages
    paths:
      - src/boilerplate/**
      - src/examples/**
      - src/protocol/**
      - src/*.html
      - src/*.include
      - src/protocol.bs
jobs:
  main:
    name: Publish Protocol to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !(github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Publish main with Bikeshed
        uses: w3c/spec-prod@v2
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          FOLDER_NAME: ${{ env.BRANCH_NAME == 'main' && '' || format('branch/{0}/', env.BRANCH_NAME) }}
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: src/protocol.bs
          DESTINATION: ${{ env.FOLDER_NAME }}protocol/index.html
