name: Publish Vocab
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - ns/**
  push:
    branches:
      - main
    paths:
      - ns/**
jobs:
  main:
    name: Publish Vocab to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            ns
      - name: Move files
        id: build
        run: |
          mkdir -p public/ns/context/
          mv ns/v1/vocab.ttl public/ns/v1.ttl
          mv ns/v1/context.json public/ns/context/v1.json-ld
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
