name: Publish Solid Guide
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - src/boilerplate/considerations.md
      - src/solid-guide/**
      - src/*.html
      - src/*.include
      - src/solid-guide.bs
  push:
    branches:
      - solid-guide
      - main
    paths:
      - src/boilerplate/considerations.md
      - src/solid-guide/**
      - src/*.html
      - src/*.include
      - src/solid-guide.bs
jobs:
  main:
    name: Publish Solid Guide to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: src/solid-guide.bs
          DESTINATION: solid-guide/index.html
