name: Publish Solid Guide
on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - src/boilerplate/considerations.md
      - src/solid-guide/**
      - src/*.html
      - src/*.include
      - src/solid-guide.bs
    types:
      - closed
  push:
    branches:
      - solid-guide
      - main
    paths:
      - src/boilerplate/considerations.md
      - src/solid-guide/**
      - src/*.html
      - src/*.include
      - src/solid-guide.bs
jobs:
  main:
    name: Publish Solid Guide to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ !(github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false) }}
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: bikeshed
          SOURCE: src/solid-guide.bs
          DESTINATION: solid-guide/index.html
