name: Publish Vocab
on:
  workflow_dispatch: {}
  pull_request:
    paths:
      - ns/**
  push:
    branches:
      - main
    paths:
      - ns/**
jobs:
  main:
    name: Publish Vocab to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: |
            ns
      - name: Get Author Stats
        run: |
          COMMIT_AUTHOR_NAME=$(git show -s --format='%an' ${{ github.sha }})
          COMMIT_AUTHOR_EMAIL=$(git show -s --format='%ae' ${{ github.sha }})
          COMMIT_HEADLINE=$(git show -s --format=%s ${{ github.sha }})
          echo "COMMIT_AUTHOR_NAME=$COMMIT_AUTHOR_NAME" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_EMAIL=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_ENV
          echo "COMMIT_HEADLINE=$COMMIT_HEADLINE" >> $GITHUB_ENV
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ns
          destination_dir: ns
          user_name: ${{ env.COMMIT_AUTHOR_NAME }}
          user_email: ${{ env.COMMIT_AUTHOR_EMAIL }}
          commit_message: |
            Publish namespace: ${{ env.COMMIT_HEADLINE }}

            SHA: ${{ github.sha }}
            Reason: ${{ github.event_name }} by ${{ github.actor }}

            Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
